version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: photogram
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5433:5432'
    volumes:
      - photogram:/var/lib/postgresql/data
    restart: always

volumes:
  photogram: